nginxApp:
  replicas: 6
  deploymentName: nginx-app
  containerName: nginx
  image:
    repository: us-central1-docker.pkg.dev/august-journey-417818/app-chart/cosmo-doc:v1
    tag: "v2"
  containerPortName: http
  containerPortNumber: 80
  containerTargetPortNumber: 80

serviceAccountName: nginx-sa

serviceName: nginx-svc